version: '3'
services:

    # docker run --name some-redis  -p 6379:6379  -d redis redis-server --appendonly yes

    redis:
      container_name: redis
      image: redis
      restart: always
      command: ["redis-server", "--appendonly", "yes"]
      ports:
        - "6379:6379"
      volumes:
        - redis-data:/data
    app:
      build: .
      command: bash -c "python manage.py runserver 0.0.0.0:8000"
      restart: always
      ports:
        - "8000:8000"
      volumes:
        - .:/django_channels2_tutorial
      depends_on:
        - redis
volumes:
    redis-data:
    pgdata:
